export const dummyTenders = [
  {
    id: 1,
    title: 'Construction of Office Building - Phase 2',
    organization: 'Government Department',
    category: 'Construction',
    budget: 5000000,
    location: 'New Delhi, India',
    deadline: '2026-06-30',
    description: 'Tender for construction of modern office building with 10 floors and parking',
    requirements: ['ISO 9001 certified', 'Experience in similar projects', 'Financial bid required'],
    documents: ['RFP.pdf', 'Technical-Specs.pdf', 'Bill-of-Materials.pdf'],
    status: 'Open',
    postedDate: '2026-05-01',
    applicants: 12,
    type: 'Government',
  },
  {
    id: 2,
    title: 'IT Infrastructure Setup - Enterprise ERP',
    organization: 'Fortune 500 Company',
    category: 'IT Services',
    budget: 2500000,
    location: 'Mumbai, India',
    deadline: '2026-06-15',
    description: 'Complete IT infrastructure setup including servers, networking, and security',
    requirements: ['Microsoft Certified Partner', 'Enterprise experience', 'Support for 3 years'],
    documents: ['Specifications.pdf', 'RFP.pdf'],
    status: 'Open',
    postedDate: '2026-05-10',
    applicants: 8,
    type: 'Private',
  },
  {
    id: 3,
    title: 'Healthcare Equipment Supply',
    organization: 'Public Hospital Network',
    category: 'Healthcare',
    budget: 1500000,
    location: 'Bangalore, India',
    deadline: '2026-06-20',
    description: 'Supply of medical equipment for 5 government hospitals',
    requirements: ['FDA certified equipment', 'Installation & training', 'Warranty: 2 years'],
    documents: ['Equipment-List.pdf', 'Quality-Standards.pdf'],
    status: 'Closing Soon',
    postedDate: '2026-04-15',
    applicants: 6,
    type: 'Government',
  },
  {
    id: 4,
    title: 'Manufacturing Equipment - Industrial Automation',
    organization: 'Automobile Manufacturer',
    category: 'Manufacturing',
    budget: 7500000,
    location: 'Pune, India',
    deadline: '2026-07-10',
    description: 'Supply and installation of automated manufacturing equipment',
    requirements: ['Industry 4.0 certified', 'IOT enabled', 'Maintenance support'],
    documents: ['Tech-Specs.pdf', 'Implementation-Plan.pdf'],
    status: 'Open',
    postedDate: '2026-05-05',
    applicants: 5,
    type: 'Private',
  },
  {
    id: 5,
    title: 'Electrical Components Supply',
    organization: 'Power Distribution Company',
    category: 'Electrical',
    budget: 3000000,
    location: 'Chennai, India',
    deadline: '2026-06-25',
    description: 'Supply of high-voltage electrical components and transformers',
    requirements: ['IEC certified', 'International standard', 'Bulk supply capability'],
    documents: ['Specifications.pdf', 'Quality-Certification.pdf'],
    status: 'Open',
    postedDate: '2026-05-08',
    applicants: 9,
    type: 'Government',
  },
]

export const dummySuppliers = [
  {
    id: 1,
    name: 'TechCorp Industries',
    category: 'IT Equipment',
    location: 'Bangalore, India',
    rating: 4.8,
    reviews: 245,
    verified: true,
    description: 'Leading supplier of enterprise IT equipment and solutions',
    gstNumber: '18AABCU9603R1Z0',
    email: 'sales@techcorp.com',
    phone: '+91 80 4141 1010',
    employees: 500,
    yearEstablished: 2010,
    certifications: ['ISO 9001', 'ISO 27001', 'Microsoft Partner'],
    products: ['Laptops', 'Servers', 'Networking Equipment', 'Storage Solutions'],
  },
  {
    id: 2,
    name: 'BuildRight Construction',
    category: 'Construction Materials',
    location: 'Mumbai, India',
    rating: 4.6,
    reviews: 189,
    verified: true,
    description: 'Premium construction materials and services provider',
    gstNumber: '27AABCU9603R2Z1',
    email: 'info@buildright.com',
    phone: '+91 22 4141 2020',
    employees: 350,
    yearEstablished: 2008,
    certifications: ['ISO 9001', 'ISO 14001'],
    products: ['Cement', 'Steel', 'Bricks', 'Concrete', 'Scaffolding'],
  },
  {
    id: 3,
    name: 'Industrial Machinery Ltd',
    category: 'Machinery',
    location: 'Pune, India',
    rating: 4.7,
    reviews: 156,
    verified: true,
    description: 'Manufacturer and supplier of industrial machinery',
    gstNumber: '27AABCU9603R3Z2',
    email: 'sales@imachinery.com',
    phone: '+91 20 4141 3030',
    employees: 450,
    yearEstablished: 2005,
    certifications: ['ISO 9001', 'CE Certified'],
    products: ['CNC Machines', 'Hydraulic Presses', 'Automation Equipment'],
  },
  {
    id: 4,
    name: 'OfficeSupply Direct',
    category: 'Office Supplies',
    location: 'Delhi, India',
    rating: 4.5,
    reviews: 312,
    verified: true,
    description: 'Comprehensive office supplies and furniture solutions',
    gstNumber: '07AABCU9603R4Z3',
    email: 'supply@officesupply.com',
    phone: '+91 11 4141 4040',
    employees: 200,
    yearEstablished: 2012,
    certifications: ['ISO 9001'],
    products: ['Furniture', 'Stationery', 'Computers', 'Printers'],
  },
  {
    id: 5,
    name: 'Green Energy Solutions',
    category: 'Electrical',
    location: 'Ahmedabad, India',
    rating: 4.9,
    reviews: 198,
    verified: true,
    description: 'Renewable energy and electrical equipment provider',
    gstNumber: '24AABCU9603R5Z4',
    email: 'info@greenenergy.com',
    phone: '+91 79 4141 5050',
    employees: 300,
    yearEstablished: 2015,
    certifications: ['ISO 9001', 'Green Certified'],
    products: ['Solar Panels', 'Transformers', 'Power Distribution Units'],
  },
]

export const dummyArticles = [
  {
    id: 1,
    title: 'Complete Guide to Government Tenders in India',
    category: 'Procurement Basics',
    author: 'Raj Kumar',
    date: '2026-05-10',
    readTime: 8,
    image: '📋',
    excerpt: 'Learn the complete process of participating in government tenders and procurement',
    content: 'Government tenders are formal invitations for bids...',
    views: 2341,
  },
  {
    id: 2,
    title: 'Strategic Sourcing: Best Practices',
    category: 'Strategic Sourcing',
    author: 'Priya Sharma',
    date: '2026-05-08',
    readTime: 12,
    image: '📊',
    excerpt: 'Master the art of strategic sourcing to reduce costs and improve quality',
    content: 'Strategic sourcing is a comprehensive approach...',
    views: 1890,
  },
  {
    id: 3,
    title: 'Supply Chain Optimization Strategies',
    category: 'Supply Chain',
    author: 'Arjun Singh',
    date: '2026-05-05',
    readTime: 10,
    image: '🚚',
    excerpt: 'Optimize your supply chain for maximum efficiency and cost savings',
    content: 'Supply chain optimization involves...',
    views: 1654,
  },
  {
    id: 4,
    title: 'Vendor Management Best Practices',
    category: 'Vendor Management',
    author: 'Neha Gupta',
    date: '2026-05-01',
    readTime: 9,
    image: '🤝',
    excerpt: 'Build strong vendor relationships and manage vendor performance',
    content: 'Effective vendor management includes...',
    views: 1432,
  },
  {
    id: 5,
    title: 'Tender Process: Step-by-Step Guide',
    category: 'Tender Process',
    author: 'Vikram Patel',
    date: '2026-04-28',
    readTime: 11,
    image: '📝',
    excerpt: 'Navigate the tender process with confidence and clarity',
    content: 'The tender process typically involves...',
    views: 2100,
  },
]

export const dummyTestimonials = [
  {
    text: 'This platform transformed our procurement process. We saved 40% on procurement costs in just 6 months!',
    author: 'Rajeev Kumar',
    role: 'Chief Procurement Officer, Tech Corp',
  },
  {
    text: 'Finding qualified suppliers has never been easier. The directory is comprehensive and verified.',
    author: 'Sunita Reddy',
    role: 'Procurement Manager, Manufacturing Ltd',
  },
  {
    text: 'The learning academy helped our team understand modern procurement practices and trends.',
    author: 'Arun Desai',
    role: 'Business Development Manager',
  },
  {
    text: 'Excellent platform with great support. The dashboard is intuitive and easy to use.',
    author: 'Priya Mehta',
    role: 'Supply Chain Director, Logistics Corp',
  },
]

export const dummyTeamMembers = [
  { id: 1, name: 'Rahul Sharma', email: 'rahul@company.com', role: 'Procurement Lead' },
  { id: 2, name: 'Anjali Verma', email: 'anjali@company.com', role: 'Sourcing Manager' },
  { id: 3, name: 'Vikram Singh', email: 'vikram@company.com', role: 'Vendor Manager' },
]

export const dummyPurchaseOrders = [
  {
    id: 'PO-001',
    vendor: 'TechCorp Industries',
    status: 'Approved',
    amount: 250000,
    date: '2026-05-10',
    items: 10,
  },
  {
    id: 'PO-002',
    vendor: 'BuildRight Construction',
    status: 'Pending',
    amount: 500000,
    date: '2026-05-12',
    items: 25,
  },
  {
    id: 'PO-003',
    vendor: 'Industrial Machinery Ltd',
    status: 'Delivered',
    amount: 1500000,
    date: '2026-05-05',
    items: 5,
  },
]